# Read more about setting it up
# https://medium.com/@ljmocic/deploying-react-application-to-aws-s3-using-github-actions-85addacaeace

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm install   
        env:
          CI: false
      - name: Generate build
        run: CI=false npm run build
      - name: Build the Docker image
        run: docker build -f Dockerfile -t kimchi1503/algo .
      - name: Publish to Docker Hub
        uses: docker/build-push-action@v1
        with:
         username: ${{ secrets.DOCKER_USER}}
         password: ${{ secrets.DOCKER_PASS}}
         repository: kimchi1503/algo
         tags: latest
      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./build
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: production-files
        path: ./build

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{secrets.token}}
        publish_dir: ./build
